### ISSUE TITLE
Consider implementing the secrets hook to prevent API token to be bundled

### ISSUE THREAD

**Issue by kmelve** [Halo-Lab/sanity-performance-plugin#3]
Since Sanity Studio is a Single Page Application then all plugin code will be bundled in the publicly accessible javascript files (unless an authenticated URL hosts it). 

While it seems like the PageSpeed API token will enable access to any sensitive data, it can in theory, let people find and utilize the token for their own.

You can implement https://github.com/sanity-io/sanity-studio-secrets to let plugin users store the secret in a non-public namespaced document. It exposes a hook that lets you set the token from the Studio.

**Comment by lazio** [comment]
Hey @kmelve, many thanks for reviewing the plugin and opening these issues. 

We've addressed both of them and has shipped an updated version to npm

**Comment by kmelve** [comment]
Awesome – thanks!
